### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by grigio** [ziahamza/webui-aria2#138]
Would you accept a PR about [Dockerfile](https://github.com/grigio/docker-apps/blob/master/web-aria2/Dockerfile) to immediatly use/test webui-aria2 in a Docker sandbox?

**Comment by ziahamza** [comment]
That would be really awesome!! With some docs in the read me it would make
it very easy to try out and deploy webui with aria2

**Comment by grigio** [comment]
Ok I'll clean it a bit, then I'll make a PR also with docs
Thanks for webui-aria2

**Comment by Allezxandre** [comment]
Hi, I see this issue is still open so I'll post here instead of creating a new one:

`goreman` seems to make `aria2c` freeze for me. The web ui always works, but sometimes it looses connection to `aria2c` that just froze. Only a restart of the container works, and these events appear randomly.

I found a way to fix this by replacing `goreman` with `supervisord` from the default repos, and it has been working on my machine without freezing for 2 days now. Do you want a Push Request with my updated Dockerfile?

**Comment by ziahamza** [comment]
Oh... I wasn't aware. Sure do send a pull request. Would love to merge in supervisor support as I use it in other projects too 


Sent by Outlook for Android





On Wed, Jun 10, 2015 at 3:38 PM -0700, "Alexandre" <notifications@github.com> wrote:












Hi, I see this issue is still open so I'll post here instead of creating a new one:



goreman seems to make aria2c freeze for me. The web ui always works, but sometimes it looses connection to aria2c that just froze. Only a restart of the container works, and these events appear randomly.



I found a way to fix this by replacing goreman with supervisord from the default repos, and it has been working on my machine without freezing for 2 days now. Do you want a Push Request with my updated Dockerfile?

**Comment by grigio** [comment]
Aaaah python dependency! :) Are you sure the problem is that? Because i don't have this issue, did you try to read the docker log when the freeze happen?

**Comment by Allezxandre** [comment]
Yes, I hate having Python as a dependency too. 

Looking at the docker logs only shows the last line before Aria freezes. So something like `Backend | download ##### ...` 

This happens when I use a lot of torrents, so I also updated Aria to 1.19 that was supposed to fix such a bug, but I still had the issue.
