### ISSUE TITLE
outrageous cpu usage

### ISSUE THREAD

**Issue by cpine505** [ziahamza/webui-aria2#142]
I was perplexed why this app uses so much cpu. Turns out the culprit is the "progress-bar progress-bar-striped" element in index.html

The getProgress(download) function fires continuously, so the browser continuously redraws the progress bar as fast as the computer will allow.

I solved this for myself by just deleting this element from index.html. I'd suggest a fix that the progress bar only updates once per second.

**Comment by vBm** [comment]
There's a settings you can enable/disable for this issue. It's located at [configuration.js](https://github.com/ziahamza/webui-aria2/blob/master/configuration.js#L28)

**Comment by xeddo** [comment]
Why is nobody bothered by this?
This is a very inconvenient issue for me, since the CPU fan runs significantly louder, thus making my otherwise silent HTPC an annoying machine. Additionally  my machine runs 24/7 and 90% CPU usage would add up on my power bill, if i were to leave the browser open.

Fortunately I was able to reduce the CPU usage to about 50% by removing the ".progress-active .progress.bar, .progress-bar.active{ [...] }" piece from bootstrap.css.
It's still not perfect, but at least half the problem is reduced without sacrificing the progress bar alltogether.

vBm, I think you are confusing the progress-bar with the "speed"-graph, which does not seem to be the issue. :)

**Comment by ziahamza** [comment]
You can change the globalTimeout in configuration. It states how often does webui talk to aria2 and update everything. Maybe increasing that to maybe 3000 (3 sec) could help too.

**Comment by xeddo** [comment]
I am surprised, but that actually reduces the interval between the CPU usage spikes.
Solves the problem for me, thank you :)

**Comment by kingdave** [comment]
I think the problem is rather in this #193

**Comment by drwyrm** [comment]
In my case it was the css progress-bar animation that was causing high cpu usage. I fixed it with:
```
--- a/js/ctrls/main.js
+++ b/js/ctrls/main.js
@@ -544,7 +544,7 @@ function(
                        case "removed":
                                return "progress-bar-warning";
                        case "active":
-                               return "active";
+                               return "";
                        case "verifing":
                                return "progress-bar-warning";
                        case "complete":

```
If you also have high CPU usage on https://css-tricks.com/examples/ProgressBars/ then the patch above should fix it for you.
