### ISSUE TITLE
The task content can't show on webui-aria2

### ISSUE THREAD

**Issue by KwToPA** [ziahamza/webui-aria2#206]
Hi

The task content can't show on Aria2 Web Frontend
I found some errors on console

this (http://i.imgur.com/iIZ86ZK.png)

and this
```
jquery-2.1.3.js:8693 GET https://token:secret@127.0.0.1:6800/jsonrpc:6800/jsonrpc?jsoncallback=jQu…xPcHRpb24iLCJwYXJhbXMiOlsidG9rZW46cGlOYXBQbGUiXX1dXQ%3D%3D&_=1460633989927 
net::ERR_CONNECTION_CLOSED
send @ jquery-2.1.3.js:8693
jQuery.extend.ajax @ jquery-2.1.3.js:8161
ariaRequest @ jsoncall.js:16
invoke @ jsoncall.js:37
invoke @ syscall.js:42
update @ rpc.js:89 js
oncall.js:46 jsonrpc disconnect!!!
```
my JSON-RPC Path is
```
https://token:secret@127.0.01:6800/jsonrpc
```
What should I do to fix this problem?

Thanks

**Comment by SlNPacifist** [comment]
Problem on screenshot: you are querying insecure resource (over http) from secure page (over https). This is not allowed in browsers.
Secure pages can only request secure content.
Aria2 allows ssl usage (see https://aria2.github.io/manual/en/html/aria2c.html#cmdoption--rpc-certificate), but it needs valid certificate. Self-signed certificates won't work either.
If you supply Aria2 with valid certificate, don't forget to enable https://aria2.github.io/manual/en/html/aria2c.html?highlight=same%20origin#cmdoption--rpc-allow-origin-all.
Your second error seems to be misconfiguration: server just drops every connection. Most likely, you tried  to use secure connection without enabling options mentioned above.

In order to make it work you need to:
* serve Aria2 using secure connection or serve your page from insecure source
* serve Aria2 and page from same source or set `--rpc-allow-origin-all=true` option

**Comment by KwToPA** [comment]
Thanks I had solved the problem

**Comment by SlNPacifist** [comment]
Well, you can close this issue then.

**Comment by KwToPA** [comment]
close

**Comment by SlNPacifist** [comment]
@KwToPA, I mean you should close this issue. It can only be closed by repo owner, who is not showing here too often or the one who opened this issue. You should have button "Close this issue" somewhere on this page.

**Comment by KwToPA** [comment]
Ooops
