### ISSUE TITLE
javascript problem..

### ISSUE THREAD

**Issue by pietrondo** [ziahamza/webui-aria2#231]
I have already posted this problem... but i don't think it is a translation problem..
before what appen when I open chrome and firefox:
![selezione_293](https://cloud.githubusercontent.com/assets/6080662/15736414/d596d770-289f-11e6-867d-77a68d2552be.png)

Ok
With firefox debug I see this on all js library:
`SyntaxError: expected expression, got '<'`

![selezione_294](https://cloud.githubusercontent.com/assets/6080662/15736443/1658c3d6-28a0-11e6-9c8e-713f0bdadbb0.png)

thx

**Comment by ziahamza** [comment]
@pietrondo which browser is this? I am loading latest webui just fine on chrome

**Comment by pietrondo** [comment]
Firefox and chrome

Il ven 3 giu 2016 13:41 hamza zia <notifications@github.com> ha scritto:

**Comment by ziahamza** [comment]
@pietrondo I just tried both chrome and firefox ... and they work for me:

<img width="1276" alt="screen shot 2016-06-03 at 7 54 22 pm" src="https://cloud.githubusercontent.com/assets/206640/15777855/10448806-29c5-11e6-8e49-4d793481eaa5.png">

I think this is because the webserver serving webui is not serving the scripts folder of webui properly.

BTW you can also try webui through: http://ziahamza.github.io/webui-aria2/ 
and input your aria2 connection details if it is public to try it out.

**Comment by jonisc** [comment]
I have the same problem with my banana PI and Edge. Even if I downloaded to my PC, restarted, reopened the index.html file I had the same problem. But as I opened the index.html for the first time everything seemed OK. I haven't resetted my browser yet but I'll try one day. Are you German too?

**Comment by jonisc** [comment]
Ok. Doesn´t work. But I have something else: if I don´t edit enything, The web Ui is ok. But immediatly if I open (no Edit) the configuration.js this issue appears. If I don´t open it everything is OK.
