### ISSUE TITLE
JavaSCript not working

### ISSUE THREAD

**Issue by powerriegel** [ziahamza/webui-aria2#251]
angular.js:68 Uncaught Error: [$injector:modulerr] Failed to instantiate module webui due to:
TypeError: Cannot read property 'Search' of undefined

All translations missing. My browsers language is German. 

I'm using Nginx. All files are loaded, no errors in Network tab of dev tools.

**Comment by Single34** [comment]
Same Issue in Chrome.

Firefox spits out this

Error: [$injector:modulerr] Failed to instantiate module webui due to:
translation is undefined
mergeTranslation@http://localaria2/js/init.js:22:7
@http://localaria2/js/init.js:41:30
invoke@http://localaria2/js/libs/angular.js:4625:16
runInvokeQueue@http://localaria2/js/libs/angular.js:4518:11
loadModules/<@http://localaria2/js/libs/angular.js:4527:11
forEach@http://localaria2/js/libs/angular.js:321:11
loadModules@http://localaria2/js/libs/angular.js:4508:5
createInjector@http://localaria2/js/libs/angular.js:4430:19
bootstrap/doBootstrap@http://localaria2/js/libs/angular.js:1710:20
bootstrap@http://localaria2/js/libs/angular.js:1731:12
@http://localaria2/js/init.js:55:3
jQuery.Callbacks/fire@http://localaria2/js/libs/jquery-2.1.3.js:3094:10
jQuery.Callbacks/self.fireWith@http://localaria2/js/libs/jquery-2.1.3.js:3206:7
.ready@http://localaria2/js/libs/jquery-2.1.3.js:3412:3
completed@http://localaria2/js/libs/jquery-2.1.3.js:3428:2

http://errors.angularjs.org/1.5.3/$injector/modulerr?p0=webui&p1=translation%20is%20undefined%0AmergeTranslation%40http%3A%2F%2Flocalaria2%2Fjs%2Finit.js%3A22%3A7%0A%40http%3A%2F%2Flocalaria2%2Fjs%2Finit.js%3A41%3A30%0Ainvoke%40http%3A%2F%2Flocalaria2%2Fjs%2Flibs%2Fangular.js%3A4625%3A16%0ArunInvokeQueue%40http%3A%2F%2Flocalaria2%2Fjs%2Flibs%2Fangular.js%3A4518%3A11%0AloadModules%2F%3C%40http%3A%2F%2Flocalaria2%2Fjs%2Flibs%2Fangular.js%3A4527%3A11%0AforEach%40http%3A%2F%2Flocalaria2%2Fjs%2Flibs%2Fangular.js%3A321%3A11%0AloadModules%40http%3A%2F%2Flocalaria2%2Fjs%2Flibs%2Fangular.js%3A4508%3A5%0AcreateInjector%40http%3A%2F%2Flocalaria2%2Fjs%2Flibs%2Fangular.js%3A4430%3A19%0Abootstrap%2FdoBootstrap%40http%3A%2F%2Flocalaria2%2Fjs%2Flibs%2Fangular.js%3A1710%3A20%0Abootstrap%40http%3A%2F%2Flocalaria2%2Fjs%2Flibs%2Fangular.js%3A1731%3A12%0A%40http%3A%2F%2Flocalaria2%2Fjs%2Finit.js%3A55%3A3%0AjQuery.Callbacks%2Ffire%40http%3A%2F%2Flocalaria2%2Fjs%2Flibs%2Fjquery-2.1.3.js%3A3094%3A10%0AjQuery.Callbacks%2Fself.fireWith%40http%3A%2F%2Flocalaria2%2Fjs%2Flibs%2Fjquery-2.1.3.js%3A3206%3A7%0A.ready%40http%3A%2F%2Flocalaria2%2Fjs%2Flibs%2Fjquery-2.1.3.js%3A3412%3A3%0Acompleted%40http%3A%2F%2Flocalaria2%2Fjs%2Flibs%2Fjquery-2.1.3.js%3A3428%3A2%0A

**Comment by powerriegel** [comment]
Same in Opera, What are we doing wront?

**Comment by IanWendy** [comment]
webui.config(['$translateProvider', function ($translateProvider) {
  $translateProvider
      .translations('en_US', translations.en_US)
      .translations('nl_NL', mergeTranslation(translations.nl_NL, translations.en_US))
      .translations('th_TH', mergeTranslation(translations.th_TH, translations.en_US))
      .translations('zh_CN', mergeTranslation(translations.zh_CN, translations.en_US))
      .translations('pl_PL', mergeTranslation(translations.pl_PL, translations.en_US))
      .translations('fr_FR', mergeTranslation(translations.fr_FR, translations.en_US))
      .translations('de_DE', mergeTranslation(translations.de_DE, translations.en_US))
      .translations('es_ES', mergeTranslation(translations.es_ES, translations.en_US))
      .translations('ru_RU', mergeTranslation(translations.ru_RU, translations.en_US))
      .translations('it_IT', mergeTranslation(translations.it_IT, translations.en_US))
      .determinePreferredLanguage();
}]);
Comments ru and it ,it's ok

**Comment by powerriegel** [comment]
Commented the ru and it languages out in js/init.js

Translations in the menu are in German then. Ok
Error messages are in Italian.

:-(

**Comment by ziahamza** [comment]
This should be fixed this now !! :)

by: https://github.com/ziahamza/webui-aria2/pull/252
