### ISSUE TITLE
feature request : Add a file manager

### ISSUE THREAD

**Issue by eddydu44** [ziahamza/webui-aria2#418]
It would be nice if we had a file manager integrated in the webui.

**Comment by no1xsyzy** [comment]
It would have been much worse than you think because it had been going be impossible to access from your browser if we had a file manager integrated in the webui-aria2.
:(
Browsers gives a high restrictions on what pages can do because you don't want your documents disappear after opening a web page well-designed for cracking your file system.

@ziahamza Can you please add an FAQ to prevent these duplicated questions? Then you can easily close the issue after answering "see FAQ" (or even without answering, from advises from Eric Raymond, _The Cathedral and the Bazaar_)

**Comment by maz-1** [comment]
It cannot be done unless you create another daemon, which makes things complicated
