### ISSUE TITLE
Getting webui to work with nginx reverse proxy

### ISSUE THREAD

**Issue by suckerfish** [ziahamza/webui-aria2#441]
Hello,

I run a docker container currently and have almost all of my services running behind a reverse proxy with letsencrypt+nginx. Many services have a 'URL Base' option that allows easy setup for this. I don't think webui-aria2 has this. 

Can this either be added, or some sort of workaround be explained in order to get this working? Thank you.

**Comment by no1xsyzy** [comment]
`webui-aria2` can just be static resources. There is no need for URL Base because there are only relative paths. That means you can just put all files into a directory of the server, and everything will work fine.
e.g., you can `git clone git://github.com/ziahamza/webui-aria2 /var/www/html/webui-aria2` and serve static with root `/var/www/html`, and visiting `http://server/webui-aria2/index.html` will give you a working webui-aria2.
