### ISSUE TITLE
Web sockets not working

### ISSUE THREAD

**Issue by jiangqinhua** [ziahamza/webui-aria2#453]
I had install the aria2 and enter the web https://ziahamza.github.io/webui-aria2/
it shows me this, help me out pls!!
Web sockets not working due to Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.

**Comment by ShenTensen** [comment]
有一个想法，在github和stackoverflow开个中文板块出来。

**Comment by no1xsyzy** [comment]
Basically 3 ways:
* Use <http://ziahamza.github.io/webui-aria2/> (HTTP instead of HTTPS) 
  * If you use HTTPS Everywhere, you can disable it for github.io.
* your own server
  * Nginx
  * Apache
  * Fork this project and create CNAME-d GitHub pages. Using CNAME since you are not using HTTP on github.io.
  * e.t.c.
* Configure your aria2 to be compatible with *WebSocket with Security*.
  * Need a domain and an SSL certificate

Reason described:
It's because it is considered unsafe and information leaking to use *WebSocket* on HTTPS pages. (Considered by those who created HTTPS)
