### ISSUE TITLE
Disable hostname verifier

### ISSUE THREAD

**Issue by devgianlu** [ziahamza/webui-aria2#455]
When trying to connect to a local address with a secure connection (eg. https://192.168.1.50/jsonrpc), the client fails to connect which is reasonable. It would be nice if we could disable the hostname verifier to allow connection in this kind of situation. I know it defeats some security features, but with a reasonable warning it should be fine.

**Comment by no1xsyzy** [comment]
As I know, it is totally impossible with IE/Chrome/Firefox/Opera/Edge. So I believe all browsers disallow that. 

What's more, you must have a certificate to start HTTPS link, otherwise, it can only produce nonsense data to your browser. Any kind of clients (including browsers) **cannot** decrypt data if the key is not known. Browsers are hard-coded to support the key sharing of HTTPS.

However, you have register a domain and a certificate. (for free domains and certs: <http://dot.tk/> and <https://letsencrypt.org/>) You may want to edit your [`hosts` file](https://en.wikipedia.org/wiki/Hosts_(file)) to use local address instead of global address for connection.

**Comment by devgianlu** [comment]
I solved this by pointing the domain to the desired machine. This is still a workaround, but it eliminates the bottleneck of the additional latency created by the remote address.
