### ISSUE TITLE
I made a cross-platform native gui for aria2,hope you like it.

### ISSUE THREAD

**Issue by hugetiny** [ziahamza/webui-aria2#491]
I made a cross-platform native gui for aria2,hope you like it.

**Comment by hugetiny** [comment]
https://github.com/hugetiny/negibox

**Comment by no1xsyzy** [comment]
Off topic. Neither front-ended nor aria 2 related.

**Comment by hugetiny** [comment]
@no1xsyzy  is based on aria2 and sovle the persist issues for web gui users

**Comment by no1xsyzy** [comment]
@hugetiny then it is illegal now, since [aria2](https://github.com/aria2/aria2) is released under a mixed license of [GPLv2](https://github.com/aria2/aria2/blob/master/COPYING) and [OpenSSL](https://github.com/aria2/aria2/blob/master/LICENSE.OpenSSL). At any time any aria2 developer (anyone who had ever contribute to aria2 prior to your version) could send DCMA Takedown to Github and you'd have only 24 hours to modify the repository. If you didn't make to satisfy that, the repository would be closed forever.
All the "source codes" available publicly are just the promoting web page.

Chinese project with a Japanese name (Negi = green/spring/bunching onion) and matrix-like Japanese katakana in the logo without Japanese introduction but a bunch of minor languages like Arabian and Thai and others that I am not able to tell the name. I suppose most of them are from Google translate, which is not a good way for i18n. To make matters worse, only Chinese Simplified/Traditional pages contain donation.
And plz fix all spell mistakes. They are distracting. Grammarly or even MS Word can help.

**Comment by hugetiny** [comment]
It's free and it's under developing and its' for everyone in the world
Please help me to fix all spell mistakes if you like.

**Comment by hugetiny** [comment]
the GNU General Public License is intended to guarantee your freedom to share and change free software--to make sure the software is free for all its users.  This General Public License applies to most of the Free Software Foundation's software and to any other program whose authors commit to using it.  (Some other Free Software Foundation software is covered by the GNU Library General Public License instead.)  You can apply it to your programs, too.    When we speak of free software, we are referring to freedom, not price.  Our General Public Licenses are designed to make sure that you have the freedom to distribute copies of free software (and charge for this service if you wish), that you receive source code or can get it if you want it, that you can change the software or use pieces of it in new free programs; and that you know you can do these things.    To protect your rights, we need to make restrictions that forbid anyone to deny you these rights or to ask you to surrender the rights. These restrictions translate to certain responsibilities for you if you distribute copies of the software, or if you modify it.    For example, if you distribute copies of such a program, whether gratis or for a fee, you must give the recipients all the rights that you have.  You must make sure that they, too, receive or can get the source code.  And you must show them these terms so they know their rights.    We protect your rights with two steps: (1) copyright the software, and (2) offer you this license which gives you legal permission to copy, distribute and/or modify the software.    Also, for each author's protection and ours, we want to make certain that everyone understands that there is no warranty for this free software.  If the software is modified by someone else and passed on, we want its recipients to know that what they have is not the original, so that any problems introduced by others will not reflect on the original authors' reputations.    Finally, any free program is threatened constantly by software patents.  We wish to avoid the danger that redistributors of a free program will individually obtain patent licenses, in effect making the program proprietary.  To prevent this, we have made it clear that any patent must be licensed for everyone's free use or not licensed at all.    The precise terms and conditions for copying, distribution and modification follow.

**Comment by no1xsyzy** [comment]
Continued discussion at <https://github.com/hugetiny/negibox/issues/6>
BTW this "Negibox" seems based on <https://github.com/mayswind/AriaNg>
@anthonyraymond @ziahamza I'm not sure how you think about this kind of promotion. I am feeling bad about it. Ghost repository and copies of codes and binaries from everywhere.

**Comment by anthonyraymond** [comment]
Won't give my opinion as i'm not the maintainer of this repo. But i'm closing for not being an issue until @ziahamza comes by.
