### ISSUE TITLE
How do I setup access to the online webui with remote access and VPN?

### ISSUE THREAD

**Issue by Remcodh** [ziahamza/webui-aria2#503]
Hey guys,

I started using Aria2 on my Nvidia Shield like a week ago and I really like the webui. At the moment i’m using the repository to open the webui but I would like to access the online webui so I can use Aria2 from all devices everywhere easily. Now when trying to connect with the same information as in the repository version it does’nt connect. After digging around I think this has to do something with the online webui using HTTPS and that for this to work I need to set RPC to secure and add an SSL certificate. Now i’m  just a noob that just want this to work really bad and would really appreciate if someone could give me a step by step guide on how to get this to work. I hope there is an easy solution for this.

My second challenge is to get the online webui working remotely over VPN. Is this just forwarding the RPC port in my router to the IP of the Nvidia shield or will it be harder to accomplish?

Thanks is advance!

**Comment by Remcodh** [comment]
I tested remote WAN access on the repository version with VPN active and it works like a charm. I just forwarded port 6800 in my router to the IP of Nvidia Shield. Now the only thing left is getting the online webui working and maybe find out how to keep incomplete downloads in a different folder, move completed downloads after they finish or append a different name to incomplete files. For this is don't see a built in option yet, but the feature request is already created by someone else which is nice!

**Comment by anthonyraymond** [comment]
You might be interested in aria2 event hooks : https://aria2.github.io/manual/en/html/aria2c.html#event-hook

**Comment by Remcodh** [comment]
Thanks man! I came across this myself too. It does seems like some work and I would prefer a built-in file move option, but hey can’t have everything. Can you help me with my biggest issue, which is connecting to the online webui?

**Comment by anthonyraymond** [comment]
Can you paste the browser's error log? CTRL + MAJ + I in chrome (maybe the same in firefox) then go to the Console tab

**Comment by sallenko** [comment]
I also have this issue. I have aria2 installed on NAS connected via USB to Asus router with Merlin firmware. Aria2 is installed through debian. 
I have a VPN client on my router and would like aria2 to download through the VPN. I noticed that I should be able to use the advance option interface and specify either ipadress or tun. I chose tun11 as my VPN. When downloading with aria2 through putty and typing "--interface=tun11" it works.

For some reason when I type interface=tun11 in the aria2.conf file and try to connect to aria2 Webui, I can not connect to the Webui, it says cannot connect to aria2 RPC server.

What changes needs to be performed in the aria2 webui in order to connect to the RPC server?
