### ISSUE TITLE
Parameters get reset after aria2 restart

### ISSUE THREAD

**Issue by agneevX** [ziahamza/webui-aria2#544]
Every time I save several parameters such as `split`, `max-concurrent-downloads`... restarting `aria2` resets it.

Starting `aria2` with the parameters doesn't work either as `webui-aria2` doesn't read it apparently. 
```
ExecStart=/usr/bin/aria2c \
        --enable-rpc \
        --rpc-listen-all \
        --max-connection-per-server=10 \
        --dir=/home/pi/down \
        --console-log-level=warn \
        --log=/home/pi/aria2.log
        --split=10 \
        --continue true 
```

How do I make the settings persist between restarts?

**Comment by no1xsyzy** [comment]
No, aria2 will not save configs from RPC interface. IMO this is better since you can easily revert any change if you set something wrong (like docker, programmers love docker because it will save time cleaning up their silly tweaking adventures).
However, it should be strange if you meant command line parameters didn't work. If they didn't work, how could you even start an RPC server? If you mean adding or removing some of them didn't make a change, remember `systemctl daemon-reload`. Otherwise, systemd will still use old unit. Another rescue is to use [`conf-path`](https://aria2.github.io/manual/en/html/aria2c.html#cmdoption-conf-path) option.

**Comment by agneevX** [comment]
If the parameters are mentioned in the systemd file, then `webui-aria2` should be able to read it without any configuration, right? Except that’s not happening.

I’ll try with `conf-path`.

**Comment by no1xsyzy** [comment]
`webui-aria2` don't read directly from the systemd file but the running instance. In RPC interface there are several methods for that. Try `ps -elf | grep aria2c` to check if the command line contains those args.

But wait a minute, I didn't check your args. I supposed your WebUI connected to the instance correctly. However, I just noticed that you didn't give `--rpc-allow-origin-all`, which is required to access aria2 instance from a different "origin" (the combination of `protocol://host:port`).

**Comment by agneevX** [comment]
Issue is no longer present.
